/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zivdigi_helloffmpeg_ZivPlayer */

#ifndef _Included_com_zivdigi_helloffmpeg_ZivPlayer
#define _Included_com_zivdigi_helloffmpeg_ZivPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zivdigi_helloffmpeg_ZivPlayer
 * Method:    nativeInit
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_zivdigi_helloffmpeg_ZivPlayer_nativeInit
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_zivdigi_helloffmpeg_ZivPlayer
 * Method:    nativeDestroy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zivdigi_helloffmpeg_ZivPlayer_nativeDestroy
  (JNIEnv *, jobject);

/*
 * Class:     com_zivdigi_helloffmpeg_ZivPlayer
 * Method:    startStream
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_zivdigi_helloffmpeg_ZivPlayer_startStream
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_zivdigi_helloffmpeg_ZivPlayer
 * Method:    stopStream
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_zivdigi_helloffmpeg_ZivPlayer_stopStream
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_zivdigi_helloffmpeg_ZivPlayer
 * Method:    setRender
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_zivdigi_helloffmpeg_ZivPlayer_setRender
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_zivdigi_helloffmpeg_ZivPlayer
 * Method:    isFrameReady
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_zivdigi_helloffmpeg_ZivPlayer_isFrameReady
  (JNIEnv *, jobject);

/*
 * Class:     com_zivdigi_helloffmpeg_ZivPlayer
 * Method:    getVideoWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zivdigi_helloffmpeg_ZivPlayer_getVideoWidth
  (JNIEnv *, jobject);

/*
 * Class:     com_zivdigi_helloffmpeg_ZivPlayer
 * Method:    getVideoHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zivdigi_helloffmpeg_ZivPlayer_getVideoHeight
  (JNIEnv *, jobject);

/*
 * Class:     com_zivdigi_helloffmpeg_ZivPlayer
 * Method:    getOutputByteSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zivdigi_helloffmpeg_ZivPlayer_getOutputByteSize
  (JNIEnv *, jobject);

jlong JNICALL JNICALL Java_com_zivdigi_helloffmpeg_ZivPlayer_decodeFrameToDirectBuffer
        (JNIEnv *env, jobject thiz, jobject out_buffer);

#ifdef __cplusplus
}
#endif
#endif
